name: flutter_sentry
description: Sentry.io error reporting plugin for Flutter, offering tight integration with Flutter and native code.
version: 0.1.0
homepage: https://github.com/dasfoo/flutter_sentry

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  sentry: ^3.0.0
  device_info: ^0.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.9.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: org.dasfoo.flutter_sentry
        pluginClass: FlutterSentryPlugin
      ios:
        pluginClass: FlutterSentryPlugin
